import type { RoleTypes } from '@/types/hero.type';
import { type HeroTypes } from '@/types/hero.type';

export const hero: HeroTypes[] = [
    {
        id: 'freya-1',
        name: 'Freya',
        image: '/hero/thumbnail-freya.png',
        description: '',
        model: '/models/hero_freya_lobby.glb',
        position: [0, 0, 8],
        size: 2.8,
        idle: 'city_idle',
        action: 'city_action',
        role: 'fighter',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
        skill: [
            '/hero/magic/skill-freya-1.png',
            '/hero/magic/skill-freya-2.png',
            '/hero/magic/skill-freya-3.png',
            '/hero/magic/skill-freya-4.png',
        ],
    },
    {
        id: 'alice-1',
        name: 'Alice',
        image: '/hero/thumbnail-alice.png',
        description: '',
        model: '/models/hero_alice_lobby.glb',
        position: [0, 0, 8],
        size: 3.8,
        idle: 'city_idle',
        action: 'city_action',
        role: 'mage',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
        skill: [
            '/hero/magic/skill-alice-1.png',
            '/hero/magic/skill-alice-2.png',
            '/hero/magic/skill-alice-3.png',
            '/hero/magic/skill-alice-4.png',
        ],
    },
    {
        id: 'wanwan-1',
        name: 'Wanwan',
        image: '/hero/thumbnail-wanwan.png',
        description: '',
        model: '/models/hero_wanwan_lobby.glb',
        position: [0, 0, 8],
        size: 3.1,
        idle: 'city_idle',
        action: 'city_action',
        role: 'marksman',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
        skill: [
            '/hero/magic/skill-wanwan-1.png',
            '/hero/magic/skill-wanwan-2.png',
            '/hero/magic/skill-wanwan-3.png',
            '/hero/magic/skill-wanwan-4.png',
        ],
    },
    {
        id: 'layla-1',
        name: 'Layla',
        image: '/hero/thumbnail-layla.png',
        description: '',
        model: '/models/hero_layla_lobby.glb',
        position: [0, 0, 8],
        size: 3.4,
        idle: 'city_idle',
        action: 'city_action',
        role: 'marksman',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
        skill: [
            '/hero/magic/skill-layla-1.png',
            '/hero/magic/skill-layla-2.png',
            '/hero/magic/skill-layla-3.png',
            '/hero/magic/skill-layla-4.png',
        ],
    },
    {
        id: 'tigreal-1',
        name: 'Tigreal',
        image: '/hero/thumbnail-tigreal.png',
        description: '',
        model: '/models/hero_tigreal_lobby.glb',
        position: [0, 0, 8],
        size: 3.5,
        idle: 'city_idle',
        action: 'city_action',
        role: 'tank',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
        skill: [
            '/hero/magic/skill-tigreal-1.png',
            '/hero/magic/skill-tigreal-2.png',
            '/hero/magic/skill-tigreal-3.png',
            '/hero/magic/skill-tigreal-4.png',
        ],
    },
    {
        id: 'carmilla-1',
        name: 'Carmilla',
        image: '/hero/thumbnail-carmilla.png',
        description: '',
        model: '/models/hero_carmilla_lobby.glb',
        position: [0, 0, 7],
        size: 350,
        idle: 'city_idle',
        action: 'city_action',
        role: 'support',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
        skill: [
            '/hero/magic/skill-carmilla-1.png',
            '/hero/magic/skill-carmilla-2.png',
            '/hero/magic/skill-carmilla-3.png',
            '/hero/magic/skill-carmilla-4.png',
        ],
    },
    {
        id: 'odette-1',
        name: 'Odette',
        image: '/hero/thumbnail-odette.png',
        description: '',
        model: '/models/hero_odette_lobby.glb',
        position: [0, 0, 8],
        size: 27.5,
        idle: 'city_idle',
        action: 'city_action',
        role: 'mage',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
        skill: [
            '/hero/magic/skill-odette-1.png',
            '/hero/magic/skill-odette-2.png',
            '/hero/magic/skill-odette-3.png',
            '/hero/magic/skill-odette-4.png',
        ],
    },
    {
        id: 'vexana-1',
        name: 'Vexana',
        image: '/hero/thumbnail-vexana.png',
        description: '',
        model: '/models/hero_vexana_old_model_lobby.glb',
        position: [0, 0, 7],
        size: 3.7,
        idle: 'city_idle',
        action: 'city_action',
        role: 'mage',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
        skill: [
            '/hero/magic/skill-vexana-1.png',
            '/hero/magic/skill-vexana-2.png',
            '/hero/magic/skill-vexana-3.png',
            '/hero/magic/skill-vexana-4.png',
        ],
    },
    {
        id: 'kagura-1',
        name: 'Kagura',
        image: '/hero/thumbnail-kagura.png',
        description: '',
        model: '/models/hero_kagura_lobby.glb',
        position: [0, 0, 7],
        size: 3.8,
        idle: 'city_idle',
        action: 'city_action',
        role: 'mage',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
        skill: [
            '/hero/magic/skill-kagura-1.png',
            '/hero/magic/skill-kagura-2.png',
            '/hero/magic/skill-kagura-3.png',
            '/hero/magic/skill-kagura-4.png',
        ],
    },
    {
        id: 'ruby-1',
        name: 'Ruby',
        image: '/hero/thumbnail-ruby.png',
        description: '',
        model: '/models/hero_ruby_old_lobby.glb',
        position: [0, 0, 7],
        size: 400,
        idle: 'city_idle',
        action: 'city_action',
        role: 'fighter',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
        skill: [
            '/hero/magic/skill-ruby-1.png',
            '/hero/magic/skill-ruby-2.png',
            '/hero/magic/skill-ruby-3.png',
            '/hero/magic/skill-ruby-4.png',
        ],
    },
    {
        id: 'valir-1',
        name: 'Valir',
        image: '/hero/thumbnail-valir.png',
        description: '',
        model: '/models/hero_valir_lobby.glb',
        position: [0, 0, 8],
        size: 410,
        idle: 'city_idle',
        action: 'city_action',
        role: 'support',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
        skill: [
            '/hero/magic/skill-valir-1.png',
            '/hero/magic/skill-valir-2.png',
            '/hero/magic/skill-valir-3.png',
            '/hero/magic/skill-valir-4.png',
        ],
    },
];

export const roleOption: RoleTypes[] = [
    {
        role: 'fighter',
        icon: '/hero/role/role-fighter.png',
    },
    {
        role: 'assasin',
        icon: '/hero/role/role-assasin.png',
    },
    {
        role: 'marksman',
        icon: '/hero/role/role-marksman.png',
    },
    {
        role: 'support',
        icon: '/hero/role/role-support.png',
    },
    {
        role: 'tank',
        icon: '/hero/role/role-tank.png',
    },
    {
        role: 'mage',
        icon: '/hero/role/role-mage.png',
    },
];
