export const hero = [
    {
        id: 'freya-1',
        name: 'Freya',
        image: '/hero/thumbnail-freya.png',
        description: '',
        model: '/models/hero_freya_lobby.glb',
        position: [0, 0, 8],
        size: 2.8,
        idle: 'city_idle',
        action: 'city_action',
        role: 'fighter',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
    },
    {
        id: 'alice-1',
        name: 'Alice',
        image: '/hero/thumbnail-alice.png',
        description: '',
        model: '/models/hero_alice_lobby.glb',
        position: [0, 0, 8],
        size: 3.8,
        idle: 'city_idle',
        action: 'city_action',
        role: 'mage',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
    },
    {
        id: 'wanwan-1',
        name: 'Wanwan',
        image: '/hero/thumbnail-wanwan.png',
        description: '',
        model: '/models/hero_wanwan_lobby.glb',
        position: [0, 0, 8],
        size: 3.1,
        idle: 'city_idle',
        action: 'city_action',
        role: 'marksman',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
    },
    {
        id: 'layla-1',
        name: 'Layla',
        image: '/hero/thumbnail-layla.png',
        description: '',
        model: '/models/hero_layla_lobby.glb',
        position: [0, 0, 8],
        size: 3.4,
        idle: 'city_idle',
        action: 'city_action',
        role: 'marksman',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
    },
    {
        id: 'tigreal-1',
        name: 'tigreal',
        image: '/hero/thumbnail-tigreal.png',
        description: '',
        model: '/models/hero_tigreal_lobby.glb',
        position: [0, 0, 8],
        size: 3.5,
        idle: 'city_idle',
        action: 'city_action',
        role: 'tank',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
    },
    {
        id: 'carmilla-1',
        name: 'Carmilla',
        image: '/hero/thumbnail-carmilla.png',
        description: '',
        model: '/models/hero_carmilla_lobby.glb',
        position: [0, 0, 7],
        size: 350,
        idle: 'city_idle',
        action: 'city_action',
        role: 'support',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
    },
    {
        id: 'odette-1',
        name: 'Odette',
        image: '/hero/thumbnail-odette.png',
        description: '',
        model: '/models/hero_odette_lobby.glb',
        position: [0, 0, 8],
        size: 27.5,
        idle: 'city_idle',
        action: 'city_action',
        role: 'mage',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
    },
    {
        id: 'vexana-1',
        name: 'vexana',
        image: '/hero/thumbnail-vexana.png',
        description: '',
        model: '/models/hero_vexana_old_model_lobby.glb',
        position: [0, 0, 7],
        size: 3.7,
        idle: 'city_idle',
        action: 'city_action',
        role: 'mage',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
    },
    {
        id: 'kagura-1',
        name: 'kagura',
        image: '/hero/thumbnail-kagura.png',
        description: '',
        model: '/models/hero_kagura_lobby.glb',
        position: [0, 0, 7],
        size: 3.8,
        idle: 'city_idle',
        action: 'city_action',
        role: 'mage',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
    },
    {
        id: 'ruby-1',
        name: 'ruby',
        image: '/hero/thumbnail-ruby.png',
        description: '',
        model: '/models/hero_ruby_old_lobby.glb',
        position: [0, 0, 7],
        size: 400,
        idle: 'city_idle',
        action: 'city_action',
        role: 'fighter',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
    },
    {
        id: 'valir-1',
        name: 'Valir',
        image: '/hero/thumbnail-valir.png',
        description: '',
        model: '/models/hero_valir_lobby.glb',
        position: [0, 0, 8],
        size: 410,
        idle: 'city_idle',
        action: 'city_action',
        role: 'support',
        stats: {
            attack: 80,
            defense: 50,
            ulti: 60,
            ability: 75,
        },
    },
];
