export const hero = [
    {
        id: 'freya-1',
        name: 'Freya',
        image: '/public/hero/thumbnail-freya.png',
        description: '',
        model: 'public/models/hero_freya_lobby.glb',
    },
    {
        id: 'alice-1',
        name: 'Alice',
        image: '/public/hero/thumbnail-alice.png',
        description: '',
        model: 'public/models/hero_alice_lobby.glb',
    },
    {
        id: 'wanwan-1',
        name: 'Wanwan',
        image: '/public/hero/thumbnail-wanwan-2.png',
        description: '',
        model: 'public/models/hero_wanwan_lobby.glb',
    },
    {
        id: 'freya-2',
        name: 'Freya',
        image: '/public/hero/thumbnail-freya.png',
        description: '',
        model: 'public/models/hero_freya_lobby.glb',
    },
    {
        id: 'alice-2',
        name: 'Alice',
        image: '/public/hero/thumbnail-alice.png',
        description: '',
        model: 'public/models/hero_alice_lobby.glb',
    },
    {
        id: 'wanwan-2',
        name: 'Wanwan',
        image: '/public/hero/thumbnail-wanwan-2.png',
        description: '',
        model: 'public/models/hero_wanwan_lobby.glb',
    },
    {
        id: 'freya-3',
        name: 'Freya',
        image: '/public/hero/thumbnail-freya.png',
        description: '',
        model: 'public/models/hero_freya_lobby.glb',
    },
    {
        id: 'alice-3',
        name: 'Alice',
        image: '/public/hero/thumbnail-alice.png',
        description: '',
        model: 'public/models/hero_alice_lobby.glb',
    },
    {
        id: 'wanwan-3',
        name: 'Wanwan',
        image: '/public/hero/thumbnail-wanwan-2.png',
        description: '',
        model: 'public/models/hero_wanwan_lobby.glb',
    },
];
